#include "Machine.h"




void Machine::change_availability()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-7274cd84:16d633d3b2b:-8000:00000000000008AA begin
{
}
// section -64--88-56-1-7274cd84:16d633d3b2b:-8000:00000000000008AA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
